### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by zeroeightysix** [FabLabsMC/fiber#26]
Fiber currently uses rather ambiguous naming for nodes in a tree.

First, take a look at wikipedia's [list of tree terminology](https://en.wikipedia.org/wiki/Tree_(data_structure)#Terminology_used_in_trees).

* `TreeItem`s are actually nodes.
* `Node`s are actually nodes with children
* `ConfigLeaf` is the base class of (this makes no sense)
  * ` ConfigNode`
  *  `ConfigValue`
  * and is the implementation of `TreeItem`

It might be interesting to change them to the following:
|Old name|New name|Which is|
|-|-|-|
|TreeItem|`Node`|Interface every node implements|
|Node|`Parent` (maybe `BranchNode`?)|Interface every node with children implements|
|ConfigLeaf|`ConfigNode`|Abstract implementation of `Node`|
|ConfigNode|`ConfigParent`|Implementation of `Parent`, extends `ConfigNode`|
|ConfigValue|`ConfigLeaf`|Implementation of a node without children. This node represents a setting. It carries a value, default value, etc. Extends `ConfigNode`|

Of course we'll have to change method and builder names:
`ConfigValueBuilder` -> `ConfigLeafBuilder`
`ConfigNodeBuilder` -> `ConfigParentBuider`
etc.

Please let me know what your opinion on this is!

**Comment by Pyrofab** [comment]
`Node` could probably be renamed to `Ancestor`, as it is intended to become an ancestor to another node.

**Comment by Pyrofab** [comment]
Another suggestion: `NodeLike` -> `PropertyGroup`

**Comment by Pyrofab** [comment]
And while we are at it, `ConfigNodeBuilder` -> `ConfigTreeBuilder`

**Comment by Pyrofab** [comment]
Also I would suggest `@Setting.Node` be renamed to `@Setting.Group`. Because it is much clearer for user-facing stuff.
