### ISSUE TITLE
Fabric checkstyle

### ISSUE THREAD

**Issue by zeroeightysix** [FabLabsMC/fiber#33]
We need to both add checkstyle and comply to fabric's standard conventions.

See https://github.com/FabLabsMC/Blueprint/commit/9cb6e940c6295a22af72bd3f6490c97ee71bfc40

**Comment by zeroeightysix** [comment]
Temporarily on hold: let's wait for https://github.com/FabricMC/fabric/issues/575 to be merged.

**Comment by kvverti** [comment]
Looks like the new module naming scheme is in effect now.
