### ISSUE TITLE
Add Serializers for Confabricate

### ISSUE THREAD

**Issue by i509VCB** [FabLabsMC/fiber#34]
This would open up capabilities to use the gson and hocon implementations of Configurate that are included with Confabricate.

I might consider adding this but I wanted to bring this up.

**Comment by zml2008** [comment]
👍 let me know if you need anything on the configurate/confabricate side to help your implementation

**Comment by zeroeightysix** [comment]
Ultimately we'd actually like to keep serializer implementations to a minimum. They're not actually used anywhere in fiber (just utility classes for the user to use). Asie originally suggested even separating the jankson serializer into a separate library.

Of course, adding another mod for each serializer is annoying. Maybe we could add compile-time only dependency on things like confabricate - and throw an error if it's not present at runtime (offloading the dependency to those who are actually using it). Though that seems.. iffy?

**Comment by zml2008** [comment]
that's reasonable - if it fits better the serializer could just go in confabricate - as long as it doesn't need a third mod either way works for me

(especially since configurate is available on its own already, confabricate already exists purely to integrate configurate with the fabric ecosystem)

**Comment by zeroeightysix** [comment]
If adding the dependency on fiber isn't a problem, please do!

All you need to do is implement `Serializer<T>` where `T` is the type of serialized objects (e.g. for JSON, `JsonElement`). Take a look at [Serializer](https://github.com/FabLabsMC/fiber/blob/master/src/main/java/me/zeroeightsix/fiber/serialization/Serializer.java) and [JanksonSerializer](https://github.com/FabLabsMC/fiber/blob/master/src/main/java/me/zeroeightsix/fiber/serialization/JanksonSerializer.java).

I'm going to close this issue for now, but if anything else comes up, feel free to re-open.
