### ISSUE TITLE
Fiber 0.21.0 fails to build due to an checkstyle-related issue

### ISSUE THREAD

**Issue by joaoh1** [FabLabsMC/fiber#55]
It seems like since after 0.20.0-2, Fiber stopped to compile normally, I found this out by seeing that there was no 0.21.0 in the maven (despite the wiki and README telling to use it), then I tried to grab it from Jitpack as a last resort, [it didn't work](https://jitpack.io/com/github/FabLabsMC/fiber/01dadfbb0a/build.log). I compiled it myself just to make sure. Yep, [it still didn't compile](https://hastebin.com/enewohocav.sql). (I manually changed Gradle to 6.3 in order to make compiling possible for my JDK, however, it shouldn't matter)

**Comment by zeroeightysix** [comment]
Thanks for reporting this! As of 9e5909f this has been fixed. `0.21.0` is now available on the maven repository.
