### ISSUE TITLE
Expose generic serialized types for the benefit of serializers.

### ISSUE THREAD

**Issue by kvverti** [FabLabsMC/fiber#58]
- `SerializedType#getErasedPlatformType() -> Class<? super T>`
- `SerializedType#getGenericPlatformType() -> Type`
- `ParameterizedSerializedType#getParameterizedType() -> ParameterizedType`

And small changes to `ConfigType`, `ConfigLeaf`, etc.

**Comment by Pyrofab** [comment]
I'm guessing the result `SerializedType#getGenericPlatformType()` is supposed to be passed to libraries that support any `Type` rather than used directly ?
As for the changes to the other classes, not sure they are needed. You can always access the `SerializableType` fairly easily.

**Comment by kvverti** [comment]
Yes. For `ConfigLeaf` and co, it's mainly turning `Class<T>` to the type-safe `Class<? super T>`.
