### ISSUE TITLE
Setting a config value to its current value with a PropertyMirror sets it to null.

### ISSUE THREAD

**Issue by joaoh1** [FabLabsMC/fiber#63]
Since Fiber 0.20.0, if you set a config value to the its current value through a PropertyMirror then get its value through the getValue method, the obtained value is null, which is a recipe for disaster. A workaround that I have been using against this issue is by doing a system where the value is obtained but when it's null, it uses the previous non-null value, however, it's being hard to maintain it.

**Comment by kvverti** [comment]
Are there any steps to reproduce?

**Comment by joaoh1** [comment]
> 
> 
> Are there any steps to reproduce?

I ended testing this myself on a [separate test mod](https://github.com/joaoh1/FiberTest), and I managed to pin-point the null issue, it wasn't the immediate act of getting the value that caused the null, it was setting the value with the same value that it had before, so, the steps are:

1) Have a config with a PropertyMirror mirrored to a value.
2) Through the PropertyMirror, set the value to the current value (ex. setting false to false)
3) Again, with the PropertyMirror, get the value, it should be a null
